# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('token', models.CharField(max_length=20, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('newsletter', models.BooleanField()),
            ],
        ),
    ]
