# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0002_remove_signature_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('share_text', models.CharField(max_length=256)),
                ('source_url', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='signature',
            options={'verbose_name': 'Unterschrift', 'verbose_name_plural': 'Unterschriften'},
        ),
        migrations.AlterField(
            model_name='signature',
            name='email',
            field=models.EmailField(max_length=256, unique=True, verbose_name='E-Mail'),
        ),
    ]
