# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0005_signature_emails_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='withdrawal_emails_sent',
            field=models.IntegerField(default=0),
        ),
    ]
