# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0006_signature_withdrawal_emails_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='withdrawal_token',
            field=models.CharField(default=None, max_length=24, null=True),
            preserve_default=False,
        ),
    ]
