# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0007_signature_withdrawal_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='withdrawal_token',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
